# Medical Prescription document placeholder names
NSS_NUMBER_PLACEHOLDER="NSS_NUMBER_PLACEHOLDER"
PATIENT_NAME_PLACEHOLDER="PATIENT_NAME_PLACEHOLDER"
CURP_PLACEHOLDER="CURP_PLACEHOLDER"
BIRTH_DATE_PLACEHOLDER="BIRTH_DATE_PLACEHOLDER"
STATE_PLACEHOLDER="STATE_PLACEHOLDER"
OFFICE_NO_PLACEHOLDER="OFFICE_NO_PLACEHOLDER"
UNITY_PLACEHOLDER="UNITY_PLACEHOLDER"
SHIFT_PLACEHOLDER="SHIFT_PLACEHOLDER"

# MAIN_MENU_OPT_NAMES
CREATE_PRESCRIPTION_OPT = 'Create prescription'
MODIFY_MEDICAL_PROFILE_OPT = 'Modify medical profile'
SHOW_MEDICAL_PROFILE_OPT = 'Show medical profile'
SET_MEDICAL_PROFILE = 'Set medical profile'

# MAIN_MENU_SKELETON
MAIN_MENU_SKELETON = [CREATE_PRESCRIPTION_OPT, SET_MEDICAL_PROFILE, MODIFY_MEDICAL_PROFILE_OPT, SHOW_MEDICAL_PROFILE_OPT]


# Menu actions
HOME_MENU_ACTION = "HOME_MENU_ACTION"