# Medical Prescription document placeholder names
NSS_NUMBER_PLACEHOLDER="NSS_NUMBER_PLACEHOLDER"
PATIENT_NAME_PLACEHOLDER="PATIENT_NAME_PLACEHOLDER"
CURP_PLACEHOLDER="CURP_PLACEHOLDER"
BIRTH_DATE_PLACEHOLDER="BIRTH_DATE_PLACEHOLDER"
STATE_PLACEHOLDER="STATE_PLACEHOLDER"
OFFICE_NO_PLACEHOLDER="OFFICE_NO_PLACEHOLDER"
UNITY_PLACEHOLDER="UNITY_PLACEHOLDER"
SHIFT_PLACEHOLDER="SHIFT_PLACEHOLDER"


# MAIN_MENU_SKELETON
MAIN_MENU_SKELETON = ['Create prescription', 'Modify medical profile', 'Show medical profile']

# Menu actions
HOME_MENU_ACTION = "HOME_MENU_ACTION"